### ISSUE TITLE
Keep fails to properly init

### ISSUE THREAD

**Issue by geoffmacintosh** [isaacazuelos/keep#5]
This occurs with ruby 2.4.0 and 2.3.3 at least.

```sh
> keep init
/Users/geoffmacintosh/Documents/keep/lib/keep/app.rb:46:in `block in run': undefined method `merge' for nil:NilClass (NoMethodError)
	from /Users/geoffmacintosh/Documents/keep/lib/keep/errors.rb:73:in `handle'
	from /Users/geoffmacintosh/Documents/keep/lib/keep/app.rb:45:in `run'
	from /Users/geoffmacintosh/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/keep-0.1.0/exe/keep:6:in `<top (required)>'
	from /Users/geoffmacintosh/.rbenv/gems/2.4.0/bin/keep:22:in `load'
	from /Users/geoffmacintosh/.rbenv/gems/2.4.0/bin/keep:22:in `<main>'
~/D/keep (master) > 
```

The fix is `mkdir ~/.keep`

Additionally, I don't think that `keep init -k /path/to/keep` works, but for different reasons. It's hard to tell though.

**Comment by isaacazuelos** [comment]
Yeah, global options need to go before the commands.
I'm not sure I like that.
